rango/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^rango/', include('rangoapp.urls', namespace='rango_nspc')),
)

if settings.DEBUG:
    urlpatterns += patterns(
        'django.views.static',
        (r'^media/(?P<path>.*)', 'serve', {'document_root': settings.MEDIA_ROOT}),)

rangoapp/urls.py
from django.conf.urls import url, patterns
from rangoapp import views


urlpatterns = patterns('',
        url(r'^$', views.index, name="index"),
        url(r'^about/$', views.about, name="about"),
        url(r'^category/(?P<category_name_slug>[\w\-]+)/$', views.category, name="category"),
        url(r'^add_category/$', views.add_category, name='add_category'),
        url(r'^category/(?P<category_name_slug>[\w\-]+)/add_page/$', views.add_page, name='add_page'),
        url(r'^goto/$', views.increment_page_view_count, name="goto"),
        url(r'^register/$', views.register, name="register"),
        url(r'^login/$', views.user_login, name="login"),
        url(r'^logout/$', views.user_logout, name="logout"),
        url(r'^like_category/$', views.like_category, name="like_category"),
        url(r'^suggest_category/$', views.suggest_category, name="suggest_category"),
        url(r'^auto_add_page/$', views.auto_add_page, name="auto_add_page"),
        )

rangoapp/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User


class Category(models.Model):

    name = models.CharField(max_length=128, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField()

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if self.views < 0:
            self.views = 0
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)


class Page(models.Model):
    category = models.ForeignKey(Category)
    title = models.CharField(max_length=128)
    url = models.URLField()
    views = models.IntegerField(default=0)

    def __str__(self):
        return self.title


class UserProfile(models.Model):
    user = models.OneToOneField(User)
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)

    def __str__(self):
        return self.user.username

rangoapp/forms.py
from django import forms
from rangoapp.models import Category, Page, UserProfile
from django.contrib.auth.models import User


class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=128, help_text='Enter the category name:')
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = Category
        fields = ('name',)


class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=128, help_text='Enter the page title here:')
    url = forms.URLField(max_length=200, help_text='Enter the page url here:')
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    class Meta:
        model = Page
        fields = ('title', 'url', 'views')

    def clean(self):
        cleaned_data = self.cleaned_data
        url = cleaned_data.get('url')
        if url and not url.startswith('http://'):
            url = 'http://' + url
            cleaned_data['url'] = url
        return cleaned_data


# not needed anymore, using django-registration-redux package
class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'password', 'email')


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('website', 'picture')

rangoapp/views.py
from django.shortcuts import render, redirect
from rangoapp.models import Category, Page
from rangoapp.forms import CategoryForm, PageForm, UserForm, UserProfileForm
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from rangoapp.bing_search import run_query


def index(request):
    category_list = Category.objects.order_by('-likes')[:5]
    page_list = Page.objects.order_by('-views')[:5]
    context_dict = {'categories': category_list, 'pages': page_list}
    return render(request, 'rangoapp/index.html', context_dict)


def about(request):
    count = request.session.get('visits')
    if not count:
        count = 0
    count += 1
    request.session['visits'] = count
    return render(request, 'rangoapp/about.html', {'visits': count})


def category(request, category_name_slug):
    context_dict = {}
    context_dict['result_list'] = None
    context_dict['query'] = None
    if request.method == 'POST':
        query = request.POST['query'].strip()
        if query:
            result_list = run_query(query)
            context_dict['result_list'] = result_list
            context_dict['query'] = query
    try:
        category = Category.objects.get(slug=category_name_slug)
        pages = Page.objects.filter(category=category).order_by('-views')
        context_dict['category'] = category
        context_dict['pages'] = pages
    except Category.DoesNotExist:
        pass

    if not context_dict['query']:
        context_dict['query'] = category.name
    return render(request, 'rangoapp/category.html', context_dict)


@login_required
def add_category(request):
    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save(commit=True)
            return index(request)
        else:
            print(form.errors)
    else:
        form = CategoryForm()
    return render(request, 'rangoapp/add_category.html', {'form': form})


@login_required
def add_page(request, category_name_slug):
    try:
        cat = Category.objects.get(slug=category_name_slug)
    except Category.DoesNotExist:
        cat = None

    if request.method == 'POST':
        form = PageForm(request.POST)
        if form.is_valid():
            if cat:
                instance = form.save(commit=False)
                instance.category = cat
                instance.save()
                return HttpResponseRedirect('/rango/category/' + cat.slug)
        else:
            print(form.errors)
    else:
        form = PageForm()
    context_dict = {'form': form, 'category': cat}
    return render(request, 'rangoapp/add_page.html', context_dict)


def register(request):
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']
            profile.save()
            return HttpResponseRedirect('/rango/login/')
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()
    return render(request, 'rangoapp/register.html', {'user_form': user_form, 'profile_form': profile_form})


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect('/rango/')
            else:
                return HttpResponse('Your rango account is disabled.')
        else:
            print("Invalid login details {0}, {1}".format(username, password))
            return HttpResponse('Invalid login details supplied.')
    else:
        return render(request, 'rangoapp/login.html', {})


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect('/rango/')


def increment_page_view_count(request):
    page_id = None
    url = '/rango/'
    if request.method == 'GET':
        if 'page_id' in request.GET:
            page_id = request.GET['page_id']
            try:
                page = Page.objects.get(id=page_id)
                page.views += 1
                page.save()
                url = page.url
            except:
                pass
    return redirect(url)


@login_required
def like_category(request):
    likes = 0
    if request.method == 'GET':
        if 'category_id' in request.GET:
            catid = request.GET['category_id']
            try:
                cat = Category.objects.get(id=int(catid))
                cat.likes += 1
                cat.save()
                likes = cat.likes
            except:
                pass
    return HttpResponse(likes)


def get_category_list(max_results=0, starts_with=''):
    cat_list = []
    if starts_with:
        try:
            cat_list = Category.objects.filter(name__istartswith=starts_with)
        except:
            pass

    if max_results > 0:
        if len(cat_list) > max_results:
            cat_list = cat_list[:max_results]

    return cat_list


def suggest_category(request):
    cat_list = []
    starts_with = ''
    if request.method == 'GET':
        starts_with = request.GET['suggestion']
    cat_list = get_category_list(8, starts_with)

    return render(request, 'rangoapp/suggested_cats.html', {'cat_list': cat_list})


@login_required
def auto_add_page(request):
    cat_id = None
    url = None
    title = None
    context_dict = {}
    if request.method == 'GET':
        cat_id = request.GET['category_id']
        url = request.GET['url']
        title = request.GET['title']
        if cat_id:
            category = Category.objects.get(id=int(cat_id))
            p = Page.objects.get_or_create(category=category, url=url, title=title)
            pages = Page.objects.filter(category=category).order_by("-views")
            context_dict['pages'] = pages
    return render(request, 'rangoapp/page_list.html', context_dict)

templates/rangoapp/about.html
{% extends 'rangoapp/base.html' %}
{% load staticfiles %}
{% block title_block %} | About{%  endblock %}
{% block body_block %}
<div class="page-header text-center">
    <h1>Rango, a place to categorize webpages</h1>
</div>
    <p>Rango is a spanish word meaning class, degree or rank. True to its name, this website allows registered users to categorize webpages based on what topic they are about. Each category has a list of web pages associated with it which are ranked according to the number of times they are viewed. The categories themselves are ranked according to their number of likes.</p>
    <!--<p>You have visited this page {{ visits }} times.</p>-->
    <img width="460" height="430" src="{% static 'images/rango.jpg' %}" alt="rango, the chameleon">
{% endblock %}

templates/rangoapp/add_category.html
{% extends 'rangoapp/base.html' %}
{% block title_block %} | Add a New Category{% endblock %}
{% block body_block %}
<div class="page-header text-center">
    <h1>Add a category</h1>
</div>
    <form method="post" action="{% url 'rango_nspc:add_category' %}" id="category_form">
        {% csrf_token %}
        {% for hidden in form.hidden_fields %}
            {{ hidden }}
        {% endfor %}

        {% for field in form.visible_fields %}
            {{ field.errors }}
            {{ field.help_text }}
            {{ field }}
        {% endfor %}
        <button class="btn btn-primary" type="submit" name="submit">Add Category</button>
    </form>
{% endblock %}

templates/rangoapp/add_page.html
{% extends 'rangoapp/base.html' %}
{% block title_block %} | {{ category.name }} | Add Page{% endblock %}
{% block body_block %}
<div class="page-header text-center">
    <h1>Add New Page to Category {{ category.name }}</h1>
</div>
    <form method="post" action="{% url 'rango_nspc:add_page' category.slug %}" id="page_form">
        {% csrf_token %}
        {% for hidden in form.hidden_fields %}
            {{ hidden }}
        {% endfor %}
        {% for field in form.visible_fields %}
            {{ field.errors }}
            {{ field.help_text }}
            {{ field }}
        {% endfor %}
        <button class="btn btn-primary" name="submit" type="submit">Add Page</button>
    </form>
{% endblock %}

templates/rangoapp/all_cats.html
{% if all_cats %}
    <ul class="nav nav-sidebar">
        {% for cat in all_cats %}
            {% if cat == act_cat %}<li class="active">{% else %}<li>{% endif %}
            <a href="{% url 'rango_nspc:category' cat.slug %}">{{ cat.name }}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <ul class="nav nav-sidebar">
            <li><strong>No categories at present</strong></li>
    </ul>
{% endif %}

templates/rangoapp/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load rangoapp_extras %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="http://getbootstrap.com/favicon.ico">

    <title>Rango{% block title_block %}{% endblock %}</title>

    <link href="http://getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="http://getbootstrap.com/examples/dashboard/dashboard.css" rel="stylesheet">
    <script type="text/javascript" src="{% static 'js/jquery-1.12.0.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/rango-ajax.js' %}"></script>
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/rango/">Rango</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
                <li><a href="{% url 'rango_nspc:index' %}">Home</a></li>
                    {% if user.is_authenticated %}
                        <li><a href="{% url 'rango_nspc:logout' %}">Logout</a></li>
                        <li><a href="{% url 'rango_nspc:add_category' %}">Add New Category</a></li>
                    {% else %}
                        <li><a href="{% url 'rango_nspc:register' %}">Register</a></li>
                        <li><a href="{% url 'rango_nspc:login' %}">Login</a></li>
                    {% endif %}
                        <li><a href="{% url 'rango_nspc:about' %}">About</a></li>
              </ul>
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
                {% block side_block %}
                    <ul class="nav nav-list">
                        <li class="nav-header">Find a category</li>
                        <form>
                            <label></label>
                            <li><input type="text" class="search-query span10" id="suggestion" name="suggestion" value="" /></li>
                        </form>
                    </ul>
                    <div id="cats">
                        {% get_all_categories category %}
                    </div>
                {% endblock %}
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
           <div>
                {% block body_block %}{% endblock %}
           </div>
        </div>
      </div>
    </div>
<!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="http://getbootstrap.com/dist/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="http://getbootstrap.com/assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>

templates/rangoapp/category.html
{% extends 'rangoapp/base.html' %}
{% block title_block %} | {% if category %}{{ category.name }}{% else %}Category{% endif %}{% endblock %}
{% block body_block %}
    {% if category %}
    <div class="page-header text-center">
        <h1>Pages categorized under {{ category.name }}</h1>
    </div>
    <p>
        <strong id="like_count">{{ category.likes }}</strong> people like this category
        {% if user.is_authenticated %}
            <button class="btn btn-primary" id="likes" type="button" data-catid="{{ category.id }}">
                <span class="glyphicon glyphicon-thumbs-up"></span>Like
            </button>
        {% endif %}
    </p>
        <div id="pages">
        {% if pages %}
            <ul class="list-group">
                {% for page in pages %}
                    <li class="list-group-item"><a href="{% url 'rango_nspc:goto' %}?page_id={{ page.id }}">{{ page.title }}</a>
                    {% if page.views > 1 %}
                    ({{ page.views }} views)
                    {% elif page.views == 1 %}
                    ({{ page.views }} view)
                    {% endif %}
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <strong>No pages currently in category.</strong>
        {% endif %}
        </div>
        {% if user.is_authenticated %}
            <a class="btn btn-primary" href="{% url 'rango_nspc:add_page' category.slug %}">Add a page to this category</a>
            <hr/>
            <h1>Search with Rango</h1>
            <form class="form-inline" id="search_form" method="post" action="{% url 'rango_nspc:category' category.slug %}">
                {% csrf_token %}
                <input class="form-control" type="text" size="50" name="query" value="{{ query }}" id="query" required />
                <input class="btn btn-primary" type="submit" name="submit" value="Search" />
            </form>

            {% if result_list %}
                <h3>Results</h3>
                <div class="list-group">
                {% for result in result_list %}
                    <div class="list-group-item">
                        <h4 class="list-group-item-heading"><a href="{{ result.link }}">{{ result.title }}</a></h4>
                        <p class="list-group-item-text">{{ result.summary }}</p>
                        <button class="btn btn-info btn-mini auto-add" type="button" data-catid="{{ category.id }}" data-url="{{ result.link }}" data-title="{{ result.title }}">Add</button>
                    </div>
                {% endfor %}
                </div>
            {% endif %}
        {% endif %}
    {% else %}
        The category you asked for does not exist.
    {% endif %}
{% endblock %}

templates/rangoapp/index.html
{% extends 'rangoapp/base.html' %}
{% block title_block %} | Categorize Webpages{% endblock %}
{% block body_block %}
    <div class="page-header text-center">
        {% if user.is_authenticated %}
            <h1>Rango says...Hello, {{ user.username }}!</h1>
        {% else %}
            <h1>Rango says... Hello, World!</h1>
        {% endif %}
    </div>
    <div class="row placeholders">
        <div class="col-xs-12 col-sm-6 placeholder">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">Top Five Categories</h3>
            </div>
        </div>
        {% if categories %}
            <ul class="list-group">
                {% for category in categories %}
                    <li class="list-group-item"><a href="{% url 'rango_nspc:category' category.slug %}">{{ category.name }}</a></li>
                {% endfor %}
            </ul>
        {% else %}
            <strong>There are no categories at present.</strong>
        {% endif %}
        </div>
        <div class="col-xs-12 col-sm-6 placeholder">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">Top Five Pages</h3>
            </div>
        </div>
        {% if pages %}
            <ul class="list-group">
                {% for page in pages %}
                    <li class="list-group-item"><a href="{% url 'rango_nspc:goto' %}?page_id={{ page.id }}">{{ page.title }}</a>
                    {% if page.views > 1 %}
                    ({{ page.views }} views)
                    {% elif page.views == 1 %}
                    ({{ page.views }} view)
                    {% endif %}
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <strong>There are no pages at present.</strong>
        {% endif %}
        </div>
    </div>
{% endblock %}

templates/rangoapp/login.html
{% extends 'rangoapp/base.html' %}
{% block head_title %} | Login{% endblock %}
{% block body_block %}
    <h1>Login to Rango</h1>
    <form id="login_form" method="post" action="{% url 'rango_nspc:login' %}">
        {% csrf_token %}
        username: <input type="text" name="username" value="" size="50" /><br/>
        password: <input type="password" name="password" value="" size="50" /><br/>
        <input type="submit" value="submit" />
    </form>
{% endblock %}

templates/rangoapp/page_list.html
{% if pages %}
    <ul class="list-group">
    {% for page in pages %}
        <li class="list-group-item"><a href="{% url 'rango_nspc:goto' %}?page_id={{ page.id }}">{{ page.title }}</a>
        {% if page.views > 1 %}
            ({{ page.views }} views)
        {% elif page.views == 1 %}
            ({{ page.views }} view)
        {% endif %}</li>
    {% endfor %}
    </ul>
{% else %}
    <strong>No pages currently in category.</strong>
{% endif %}

templates/rangoapp/register.html
{% extends 'rangoapp/base.html' %}
{% block head_title %} | Register{% endblock %}
{% block body_block %}
    <div class="page-header text-center">
        <h1>Register with Rango</h1>
    </div>
    {% if user.is_authenticated %}
        <strong>You are already registered!</strong>
    {% else %}
        <form method="post" action="{% url 'rango_nspc:register' %}" id="registration_form" enctype="multipart/form-data">
            {% csrf_token %}
            {{ user_form.as_p }}
            {{ profile_form.as_p }}
            <input class="btn btn-primary" type="submit" value="Register" />
        </form>
    {% endif %}
{% endblock %}

templates/rangoapp/suggested_cats.html
{% if cat_list %}
    <ul class="nav nav-sidebar">
        {% for cat in cat_list %}
            <li><a href="{% url 'rango_nspc:category' cat.slug %}">{{ cat.name }}</a></li>
        {% endfor %}
    </ul>
{% endif %}